# Multi-Role Pipeline for AI Agent Workflow
# 
# Required Repository Configuration:
# 1. Environments (Settings → Environments):
#    Create these environments exactly as named:
#    - Name: dev
#      URL: https://dev.example.com
#      Protection rules: None
#    - Name: test
#      URL: https://test.example.com
#      Protection rules:
#        - Required reviewers: None
#        - Wait timer: None
#        - Deployment branches: All
#    - Name: staging
#      URL: https://staging.example.com
#      Protection rules:
#        - Required reviewers: None
#        - Wait timer: None
#        - Deployment branches: All
#    - Name: prod
#      URL: https://prod.example.com
#      Protection rules:
#        - Required reviewers: 1
#        - Wait timer: 10 minutes
#        - Deployment branches: main only
#
# 2. Repository Variables (Settings → Secrets and variables → Actions → Variables):
#    - PYTHON_VERSION: '3.11'
#    - AWS_REGION: 'us-east-1'
#
# 3. Repository Secrets (Settings → Secrets and variables → Actions → Secrets):
#    - GEMINI_API_KEY: API key for Gemini AI model
#    - AWS_ACCESS_KEY_ID: AWS access key for deployments
#    - AWS_SECRET_ACCESS_KEY: AWS secret key for deployments
#    - AWS_ROLE_ARN: AWS role ARN for monitoring and analytics
#
# Note: The context access warnings for secrets can be safely ignored
# as long as the secrets are properly configured in the repository settings.

name: AI Agent Workflow Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: '3.11'
  ACTIONS_STEP_DEBUG: true  # Enable step debugging
  ACTIONS_RUNNER_DEBUG: true  # Enable runner debugging

jobs:
  validate_secrets:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    outputs:
      aws_region: ${{ vars.AWS_REGION }}
    steps:
      - name: Validate Secrets
        id: validate
        run: |
          # Check required secrets
          if [[ -z "${{ secrets.GEMINI_API_KEY }}" ]]; then
            echo "::error::GEMINI_API_KEY is not set"
            exit 1
          fi
          if [[ -z "${{ secrets.AWS_ROLE_ARN }}" ]]; then
            echo "::error::AWS_ROLE_ARN is not set"
            exit 1
          fi
          echo "All required secrets are set"
          
      - name: Validate Environment Variables
        id: validate_env
        run: |
          # Check required variables
          if [[ -z "${{ vars.AWS_REGION }}" ]]; then
            echo "::error::AWS_REGION variable is not set"
            exit 1
          fi
          echo "aws_region=${{ vars.AWS_REGION }}" >> $GITHUB_OUTPUT
          echo "All required variables are set"

  initial_analysis:
    needs: [validate_secrets]
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        role: [product-manager, brainstorm-facilitator, architect]
        include:
          - role: product-manager
            artifact: PRODUCT_SPECS.md
          - role: brainstorm-facilitator
            artifact: BRAINSTORM_OUTCOME.md
          - role: architect
            artifact: SYSTEM_ARCHITECTURE.md
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ needs.validate_secrets.outputs.aws_region }}
        run: |
          # Convert role name to module format (replace - with _)
          module_name="${{ matrix.role }}"
          module_name=${module_name//-/_}
          python -m ai_agents.${module_name} execute
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-analysis
          path: artifacts/${{ matrix.artifact }}
          retention-days: 5
          compression-level: 9
          overwrite: false

  planning_and_implementation:
    needs: [initial_analysis]
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        role: [planner, engineer]
        include:
          - role: planner
            artifact: PLAN.md
          - role: engineer
            artifact: COMMIT_SUMMARY.md
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-analysis'
          merge-multiple: true
          path: artifacts
      - name: Run Planning
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ needs.validate_secrets.outputs.aws_region }}
        run: |
          # Convert role name to module format (replace - with _)
          module_name="${{ matrix.role }}"
          module_name=${module_name//-/_}
          python -m ai_agents.${module_name} execute
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-output
          path: artifacts/${{ matrix.artifact }}
          retention-days: 5
          compression-level: 9
          overwrite: false

  quality_assurance:
    needs: [planning_and_implementation]
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      id-token: write
    outputs:
      test_url: ${{ steps.deploy_test.outputs.url }}
    strategy:
      matrix:
        role: [reviewer, qa_engineer]
        include:
          - role: reviewer
            artifact: REVIEW.md
          - role: qa_engineer
            artifact: TEST_DEBUG_REPORT.md
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-output'
          merge-multiple: true
          path: artifacts
      - name: Deploy Test Environment
        id: deploy_test
        run: echo "url=https://test.example.com" >> $GITHUB_OUTPUT
      - name: Run QA
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ needs.validate_secrets.outputs.aws_region }}
        run: |
          # Convert role name to module format (replace - with _)
          module_name="${{ matrix.role }}"
          module_name=${module_name//-/_}
          python -m ai_agents.${module_name} execute
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-output
          path: artifacts/${{ matrix.artifact }}
          retention-days: 5
          compression-level: 9
          overwrite: false

  deploy_staging:
    needs: [quality_assurance]
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      id-token: write
    outputs:
      staging_url: ${{ steps.deploy_staging.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ needs.validate_secrets.outputs.aws_region }}
      - name: Deploy to Staging
        id: deploy_staging
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ needs.validate_secrets.outputs.aws_region }}
        run: |
          echo "url=https://staging.example.com" >> $GITHUB_OUTPUT
          # Add your deployment steps here
      - uses: actions/upload-artifact@v4
        with:
          name: staging-deployment
          path: artifacts/DEPLOYMENT_LOG.md
          retention-days: 5
          compression-level: 9
          overwrite: false

  deploy_production:
    needs: [deploy_staging]
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    outputs:
      prod_url: ${{ steps.deploy_prod.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ needs.validate_secrets.outputs.aws_region }}
      - name: Deploy to Production
        id: deploy_prod
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ needs.validate_secrets.outputs.aws_region }}
        run: |
          echo "url=https://prod.example.com" >> $GITHUB_OUTPUT
          # Add your deployment steps here
      - uses: actions/upload-artifact@v4
        with:
          name: production-deployment
          path: artifacts/DEPLOYMENT_LOG.md
          retention-days: 5
          compression-level: 9
          overwrite: false

  monitoring_and_analytics:
    needs: [deploy_production]
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ needs.validate_secrets.outputs.aws_region }}
      - name: Run Monitoring
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ needs.validate_secrets.outputs.aws_region }}
        run: |
          python -m ai_agents.monitoring_analytics execute
