# Multi-Role Pipeline for AI Agent Workflow
# 
# Required Repository Configuration:
# 1. Environments (Settings → Environments):
#    Create these environments exactly as named:
#    - Name: test
#      URL: https://test.example.com
#      Protection rules: None
#    - Name: staging
#      URL: https://staging.example.com
#      Protection rules:
#        - Required reviewers: None
#        - Wait timer: None
#        - Deployment branches: All
#    - Name: production
#      URL: https://prod.example.com
#      Protection rules:
#        - Required reviewers: 1
#        - Wait timer: 10 minutes
#        - Deployment branches: main only
#
# 2. Repository Variables (Settings → Secrets and variables → Actions → Variables):
#    - PYTHON_VERSION: '3.11'
#    - AWS_REGION: 'us-east-1'
#
# 3. Repository Secrets (Settings → Secrets and variables → Actions → Secrets):
#    - GEMINI_API_KEY: API key for Gemini AI model
#    - AWS_ACCESS_KEY_ID: AWS access key for deployments
#    - AWS_SECRET_ACCESS_KEY: AWS secret key for deployments
#    - AWS_ROLE_ARN: AWS role ARN for monitoring and analytics
#
# Note: The context access warnings for secrets can be safely ignored
# as long as the secrets are properly configured in the repository settings.

name: AI Agent Workflow Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: '3.11'
  ACTIONS_STEP_DEBUG: true  # Enable step debugging
  ACTIONS_RUNNER_DEBUG: true  # Enable runner debugging

jobs:
  validate_secrets:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Validate Secrets
        id: validate
        run: |
          # Check required secrets
          if [[ -z "${{ secrets.GEMINI_API_KEY }}" ]]; then
            echo "::error::GEMINI_API_KEY is not set"
            exit 1
          fi
          if [[ -z "${{ secrets.AWS_ROLE_ARN }}" ]]; then
            echo "::error::AWS_ROLE_ARN is not set"
            exit 1
          fi
          echo "All required secrets are set"
          
      - name: Validate Environment Variables
        id: validate_env
        run: |
          # Check required variables
          if [[ -z "${{ vars.AWS_REGION }}" ]]; then
            echo "::error::AWS_REGION variable is not set"
            exit 1
          fi
          echo "All required variables are set"

  initial_analysis:
    needs: [validate_secrets]
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        role: [product-manager, brainstorm-facilitator, architect]
        include:
          - role: product-manager
            artifact: PRODUCT_SPECS.md
          - role: brainstorm-facilitator
            artifact: BRAINSTORM_OUTCOME.md
          - role: architect
            artifact: SYSTEM_ARCHITECTURE.md
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Convert role name to module format (replace - with _)
          module_name="${{ matrix.role }}"
          module_name=${module_name//-/_}
          python -m ai_agents.${module_name} execute
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.role }}-analysis
          path: artifacts/${{ matrix.artifact }}
          retention-days: 5
          compression-level: 9
          overwrite: false

  planning_and_implementation:
    needs: [initial_analysis]
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        role: [planner, engineer]
        include:
          - role: planner
            artifact: PLAN.md
            artifact_name: planner-output
          - role: engineer
            artifact: |
              src/**/*
              tests/**/*
              artifacts/COMMIT_SUMMARY.md
            artifact_name: engineer-output
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-analysis'
          merge-multiple: true
          path: artifacts
      - name: Execute Role
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Create artifacts directory if needed
          mkdir -p artifacts
          # Run role
          python -m ai_agents.${{ matrix.role }} execute
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact }}
          retention-days: 5
          compression-level: 9
          overwrite: false

  quality_assurance:
    needs: [planning_and_implementation]
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: ${{ steps.deploy.outputs.url }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        role: [reviewer, qa_engineer]
        include:
          - role: reviewer
            artifact: REVIEW.md
            artifact_name: review-output
          - role: qa_engineer
            artifact: TEST_DEBUG_REPORT.md
            artifact_name: qa-output
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-output'
          merge-multiple: true
          path: artifacts
      - name: Run QA Tasks
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Create artifacts directory if needed
          mkdir -p artifacts
          # Run QA
          python -m ai_agents.${{ matrix.role }} execute
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: artifacts/${{ matrix.artifact }}
          retention-days: 5
          compression-level: 9
          overwrite: false

  deploy_staging:
    needs: [quality_assurance]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.url }}
    concurrency: 
      group: staging_environment
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-output'
          merge-multiple: true
          path: artifacts
      - name: Deploy to Staging
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Create artifacts directory if needed
          mkdir -p artifacts
          # Deploy
          python -m ai_agents.devops_manager deploy --environment staging
      - uses: actions/upload-artifact@v4
        with:
          name: staging-deployment
          path: artifacts/DEPLOYMENT_LOG.md
          retention-days: 5
          compression-level: 9
          overwrite: false

  deploy_production:
    needs: [deploy_staging]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    concurrency: 
      group: production_environment
      cancel-in-progress: true
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/download-artifact@v4
        with:
          pattern: '*-output'
          merge-multiple: true
          path: artifacts
      - name: Deploy to Production
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Create artifacts directory if needed
          mkdir -p artifacts
          # Deploy
          python -m ai_agents.devops_manager deploy --environment production
      - uses: actions/upload-artifact@v4
        with:
          name: production-deployment
          path: artifacts/DEPLOYMENT_LOG.md
          retention-days: 5
          compression-level: 9
          overwrite: false

  monitoring_and_analytics:
    needs: [deploy_production]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Run Monitoring Analysis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          # Convert role name to module format (replace - with _)
          module_name="${{ matrix.role }}"
          module_name=${module_name//-/_}
          python -m ai_agents.${module_name} execute
